ktor:
    application:
        modules:
            - fr.miage.m1.ApplicationKt.module
    deployment:
        port: 8080

        requestReadTimeoutSeconds: 300
        connectionIdleTimeoutSeconds: 300
